version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file lambda-template.yml --s3-bucket photos-lambda-pipeline-bucket --output-template-file lambda-output-template.yml
artifacts:
  type: zip
  files:
    - lambda-template.yml
    - lambda-output-template.yml