version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file code-pipeline/lambdas-pipeline/lambda-template.yml --s3-bucket photos-lambda-pipeline-bucket --output-template-file lambda-output-template.yml
artifacts:
  files:
    - lambda-output-template.yml